ARC-313 feat: cover web app with e2e tests

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -52,3 +52,14 @@ fi
 
 echo "Running build..."
 npm run build
+
+# Run web e2e tests before commiting
+echo "Running e2e tests..."
+cd apps/web
+pnpm run test:e2e || {
+  echo "❌ E2E tests failed. Please fix them before commiting."
+  exit 1
+}
+cd ../..
+echo "✅ E2E tests passed"
+
